package javaTest.test5.io;
import java.io.*;
public class IOtest3 {
    public static void main(String[] args) throws IOException{
		File f1 = new File("./javaTest/test5/io/aaa.txt");
		FileInputStream fis = new FileInputStream(f1);
		int a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); a1 =fis.read();
		System.out.println((char)a1); 
		System.out.println((char)a1); 
		fis.close();
    }
}
